# -*- coding: utf-8 -*-
"""Lição de Casa

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tFRNVw6AbNJsw9NL8qq87Z0H8EDXTfLP
"""

# Solicitando informações ao usuário
nome = input("Digite o nome: ")
sobrenome = input("Digite o sobrenome: ")
idade = input("Digite a idade: ")
cidade = input("Digite a cidade: ")
ddd = input("Digite o DDD: ")
telefone = input("Digite o telefone: ")

# Imprimindo o nome completo em uma única linha
nome_completo = nome + " " + sobrenome
print("Nome completo:", nome_completo)

# Imprimindo o telefone com DDD em uma única linha
telefone_completo = f"({ddd}) {telefone}"
print("Telefone com DDD:", telefone_completo)

# Imprimindo a idade e a cidade
print("Idade:", idade)
print("Cidade:", cidade)

# Convertendo a string para maiúsculo
s = "Mentorama"
s = s.upper()

# Imprimindo a string de trás para frente
reversed_string = s[::-1]
print(reversed_string)

# Imprimindo somente as vogais
vowels = [char for char in reversed_string if char in "AEIOU"]
print(''.join(vowels))

import math

# Solicita os coeficientes a, b e c
a = float(input("Digite o coeficiente a: "))
b = float(input("Digite o coeficiente b: "))
c = float(input("Digite o coeficiente c: "))

# Calcula o discriminante
delta = b**2 - 4*a*c

# Verifica as condições e calcula as raízes
if delta > 0:
    # Duas raízes reais distintas
    x1 = (-b + math.sqrt(delta)) / (2*a)
    x2 = (-b - math.sqrt(delta)) / (2*a)
    print("As raízes são:", x1, "e", x2)
elif delta == 0:
    # Uma raiz real
    x = -b / (2*a)
    print("A raiz é:", x)
else:
    # Não há raízes reais
    print("Não há raízes reais.")

# Solicita os coeficientes a, b e c
a = float(input("Digite o coeficiente a: "))
b = float(input("Digite o coeficiente b: "))
c = float(input("Digite o coeficiente c: "))

# Calcula o discriminante
delta = b**2 - 4*a*c

# Verifica as condições e calcula as raízes
if delta > 0:
    # Duas raízes reais distintas
    x1 = (-b + delta**0.5) / (2*a)
    x2 = (-b - delta**0.5) / (2*a)
    print("As raízes são:", x1, "e", x2)
elif delta == 0:
    # Uma raiz real
    x = -b / (2*a)
    print("A raiz é:", x)
else:
    # Não há raízes reais
    print("Não há raízes reais.")

numeros_pares = 0
numeros_impares = 0
soma_pares = 0
soma_impares = 0


for num in range(1, 11):
    if num % 2 == 0:  
        numeros_pares += 1 
        soma_pares += num 
    else:
        numeros_impares += 1  
        soma_impares += num  

print("Quantidade de números pares:", numeros_pares)
print("Quantidade de números ímpares:", numeros_impares)
print("Soma dos números pares:", soma_pares)
print("Soma dos números ímpares:", soma_impares)

num = 1
numeros_pares = 0
numeros_impares = 0
soma_pares = 0
soma_impares = 0

while num <= 10:
    if num % 2 == 0:  
        numeros_pares += 1 
        soma_pares += num  
    else:
        numeros_impares += 1  
        soma_impares += num  
    num += 1  


print("Quantidade de números pares:", numeros_pares)
print("Quantidade de números ímpares:", numeros_impares)
print("Soma dos números pares:", soma_pares)
print("Soma dos números ímpares:", soma_impares)

numeros = range(1, 11)
soma = sum(numeros)

for num in numeros:
    print(num)

print("A soma dos números é:", soma)

num1 = float(input("Digite o primeiro número: "))
num2 = float(input("Digite o segundo número: "))

print("Escolha a operação que deseja realizar:")
print("1 - Soma")
print("2 - Subtração")
print("3 - Multiplicação")
print("4 - Divisão")

opcao = int(input("Digite sua opção (1/2/3/4): "))

if opcao == 1:
    resultado = num1 + num2
    print("O resultado da soma é: ", resultado)
elif opcao == 2:
    resultado = num1 - num2
    print("O resultado da subtração é: ", resultado)
elif opcao == 3:
    resultado = num1 * num2
    print("O resultado da multiplicação é: ", resultado)
elif opcao == 4:
    resultado = num1 / num2
    print("O resultado da divisão é: ", resultado)
else:
    print("Opção inválida. Por favor, escolha uma opção válida.")

a = 2
b = 5
c = 5
x = a+b+c
x

num = 1
while num <= 10:
    print(num)
    num += 1

nome = input("seu nome: ")
print ("meu nome é ",nome)

x = (5*a)*(3*b)
a = 2
b = 5
x